import type { Project } from "@/types/Project";

export const projects: Project[] = [
  {
    id: "portfolio",
    name: "Portfolio",
    stacks: ["Nuxt", "Figma"],
    img: "/images/previews/portfolio.png",
    year: "2024",
    websiteUrl: "https://hugomandou.fr",
    githubUrl: "https://github.com/Atlenexe/Portfolio-2024",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eget gravida turpis. Ut fringilla vehicula elit non finibus. Quisque consequat eu elit vel vestibulum. Quisque ante ligula, vehicula ut nibh ut, venenatis dignissim mauris. Fusce neque eros, dapibus non lacus eu, vehicula congue diam. Donec dapibus eleifend nisi id elementum. Curabitur sit amet sollicitudin orci.",
  },
  {
    id: "supermaxiplanefight",
    name: "Super maxi plane fight (WIP)",
    stacks: ["HTML", "Javascript"],
    img: "",
    year: "2024",
    websiteUrl: null,
    githubUrl: "https://github.com/Atlenexe/supermaxiplanefight",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eget gravida turpis. Ut fringilla vehicula elit non finibus. Quisque consequat eu elit vel vestibulum. Quisque ante ligula, vehicula ut nibh ut, venenatis dignissim mauris. Fusce neque eros, dapibus non lacus eu, vehicula congue diam. Donec dapibus eleifend nisi id elementum. Curabitur sit amet sollicitudin orci.",
  },
  {
    id: "neobloom",
    name: "Neo bloom",
    stacks: ["Next.js", "Figma"],
    img: "/images/previews/neobloom.png",
    year: "2023",
    websiteUrl: "https://neo-bloom.vercel.app/",
    githubUrl: "https://github.com/Atlenexe/Hackathon-ECV-2023",
    content: "",
  },
  {
    id: "acrousthetime",
    name: "Acrous the time",
    stacks: ["Next.js", "Docker", "Figma"],
    img: "/images/previews/acrousthetime.png",
    year: "2023",
    websiteUrl: null,
    githubUrl: null,
    content: "",
  },
  {
    id: "flaguesser",
    name: "Flaguesser",
    stacks: ["Angular", "Figma"],
    img: "/images/previews/flaguesser.png",
    year: "2022",
    websiteUrl: "https://flaguesser.vercel.app/",
    githubUrl: "https://github.com/Atlenexe/Flaguesser",
    content: "",
  },
  {
    id: "fichepaie",
    name: "Refonte Fiche-paie.net",
    stacks: ["Angular", "Symfony", "Docker", "Figma"],
    img: "/images/previews/fichepaie.png",
    year: "2022-2023",
    websiteUrl: "https://www.fiche-paie.net/",
    githubUrl: null,
    content: "",
  },
  {
    id: "proxinnov",
    name: "Proxinnov",
    stacks: ["HTML", "Javascript", "NodeJs"],
    img: "/images/previews/proxinnov.png",
    year: "2022",
    websiteUrl: null,
    githubUrl: null,
    content: "",
  },
];
